# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrendRoadChartsKitSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TrendRoadChartsKitSample
  #pod 'TrendRoadChartsKit', :path => './../TrendRoadChartsKit'

  target 'TrendRoadChartsKitSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrendRoadChartsKitSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
